export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS';
export const GET_RESTAURANT_DETAILS = 'GET_RESTAURANT_DETAILS';
export const CREATE_RESTAURANT_DETAILS = 'CREATE_RESTAURANT_DETAILS';
export const UPLOAD_IMAGE_RESTAURANT = 'UPLOAD_IMAGE_RESTAURANT';
