export const SELECT_RESTAURANTS = 'SELECT_RESTAURANTS';
export const SELECT_RESTAURANT = 'SELECT_RESTAURANT';
export const INSERT_RESTAURANT = 'INSERT_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const UPLOAD_IMAGE_RESTAURANT = 'UPLOAD_IMAGE_RESTAURANT';
