export const SELECT_MEALS = 'SELECT_MEALS';
export const SELECT_MEAL = 'SELECT_MEAL';
export const INSERT_MEAL = 'INSERT_MEAL';
export const UPDATE_MEAL = 'UPDATE_MEAL';
export const DELETE_MEAL = 'DELETE_MEAL';
export const SELECT_MEAL_METADATA = 'GET_MEAL_METADATA';
