export const GET_ALL_MEALS = 'GET_ALL_MEALS';
export const GET_MEAL_DETAILS = 'GET_MEAL_DETAILS';
export const CREATE_MEAL_DETAILS = 'CREATE_MEAL_DETAILS';
export const GET_MEAL_METADATA = 'GET_MEAL_METADATA';
