export const GET_ALL_CART_ITEMS = 'GET_ALL_CART_ITEMS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREMENT_CART_ITEM = 'INCREMENT_CART_ITEM';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
