export const GET_ALL_MENUS = 'GET_ALL_MENUS';
export const GET_MENU_DETAILS = 'GET_MENU_DETAILS';
export const GET_ALL_MENU_CATEGORIES = 'GET_ALL_MENU_CATEGORIES';
export const CREATE_MENU_DETAILS = 'CREATE_MENU_DETAILS';
