export const SELECT_MENUS = 'SELECT_MENUS';
export const SELECT_MENU = 'SELECT_MENU';
export const SELECT_MENU_CATEGORIES = 'SELECT_MENU_CATEGORIES';
export const INSERT_MENU = 'INSERT_MENU';
export const UPDATE_MENU = 'UPDATE_MENU';
export const DELETE_MENU = 'DELETE_MENU';
